name: Manual release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Add-on version'
        required: true
        default: '0.0.0'
      prerelease:
        description: 'True if this is a prerelease'
        type: boolean
        required: false
        default: false
jobs:
  buildAndUpload:
    uses: nvdaes/nvdaAddonWorkflows/.github/workflows/manualRelease.yaml
    with:
      version: ${{ inputs.version }}
      prerelease: ${{ inputs.prerelease }}
    
    
